### ISSUE TITLE
[m68k] Allow pass registers list in MOVEM

### ISSUE THREAD

**Issue by hansbonini** [ARM9/bass#19]
Allow pass register list in MOVEM instruction. Like:
```
movem.l d0-d4/a0-a4,-(a7) 
```

**Comment by PeterLemon** [comment]
Hi hansbonini,

Right now bass can't handle register lists in the form that many 68k assemblers use without a modification to the assembler itself.
I do allow the movem opcodes to use the raw data for these register lists in the opcodes currently, & I think you could make a giant include file with constants to any required register lists to work with these opcodes data fields as they work currently.
(You can check the MegaDrive & Neo-Geo test files to see how the movem opcodes take data instead of register lists).

**Comment by hansbonini** [comment]
I'll work on something to improve this... right?

**Comment by PeterLemon** [comment]
Hi hansbonini,
Yep of course you can try, but I feel you will find it harder than you 1st thought! Good luck anyway ;)

**Comment by thar0x29a** [comment]
Hi. This kind of feature is not 'sane' to be done with our current table parser since its includes alot of logik on the construction end of that process. 
You could (and should) do an custom parser class (see v15 or v17 brach) that will handle this case in a native way.
