### ISSUE TITLE
macro space bug

### ISSUE THREAD

**Issue by Frain-Breeze** [ARM9/bass#24]
when compiling a source file, the following macro works fine: `macro fine (variable foo) {
}`.
The macro `macro bad (variable bar){
}` however, does not. The compiler doesn't notice the `{` if you don't add a space in front of it.

**Comment by ARM9** [comment]
This is a known bug (feature) in the parser because spaces are part of the grammar, see https://github.com/ARM9/bass/blob/master/bass/core/analyze.cpp#L43

The correct way to fix this is to tokenize the input before parsing. An easier fix would be to add a `\s+` rule to string.match and also integrate that with the table parser to get rid of the whitespace hack in the parser.

**Comment by thar0x29a** [comment]
This will not change in the near future since the bass lexing is based on space seperation, not on character by character. 
It remains a feature

**Comment by thar0x29a** [comment]
ill take a look at it. hopefully soon

**Comment by thar0x29a** [comment]
This was a though decision but .. We will not do that for now. 
Sooner or later we will redo the lexor and adress this issue. But for now it wont make sense to handle it by making case based changes.
